name: CI
on: [push,pull_request]

jobs:
  test-bmp-tga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create configure
        run: |
          sudo apt-get update -y
          sudo apt-get install autoconf automake libtool gcc gimp libgimp2.0-dev
          autoreconf -i
          automake
      - name: Choose configure
        run: ./configure --enable-debugtime
      - name: Do a make
        run: make
      - name: Run bmp test1
        run: |
          cd tests
          make update-tests
          ./test1.sh
          cd ..
      - name: Run tga test2
        run: |
          cd tests
          ./test2.sh
          cd ..
